<?php
/**
 * @var $block Rewarding
 */
$isRewards = $block->manageRewarding();
$campaignId = $block->getCampaignId();

use Cardoso\ViralLoops\Block\Logged\Rewarding;

?>
<?php if ($block->isEnable()) : ?>
<script>

    !function() {
        var a = window.VL = window.VL || {};
        return a.instances = a.instances || {}, a.invoked ? void(window.console && console.error && console.error("VL snippet loaded twice.")) : (a.invoked = !0, void(a.load = function(b, c, d) {
            var e = {};
            e.publicToken = b, e.config = c || {};
            var f = document.createElement("script");
            f.type = "text/javascript", f.id = "vrlps-js", f.defer = !0, f.src = "https://app.viral-loops.com/client/vl/vl.min.js";
            var g = document.getElementsByTagName("script")[0];
            return g.parentNode.insertBefore(f, g), f.onload = function() {
                a.setup(e), a.instances[b] = e
            }, e.identify = e.identify || function(a, b) {
                e.afterLoad = {
                    identify: {
                        userData: a,
                        cb: b
                    }
                }
            }, e.pendingEvents = [], e.track = e.track || function(a, b) {
                e.pendingEvents.push({
                    event: a,
                    cb: b
                })
            }, e.pendingHooks = [], e.addHook = e.addHook || function(a, b) {
                e.pendingHooks.push({
                    name: a,
                    cb: b
                })
            }, e.$ = e.$ || function(a) {
                e.pendingHooks.push({
                    name: "ready",
                    cb: a
                })
            }, e
        }))
    }();
    var campaign = VL.load("<?= $campaignId; ?>", {
        autoLoadWidgets: !0
    });
    campaign.addHook("boot", function() {
        campaign.widgets.create("rewardingWidget", {
            container: "body",
            position: "bottom-left"
        }), campaign.widgets.create("rewardingWidgetTrigger", {
            container: "body",
            position: "bottom-left"
        })
    });
    setTimeout(() => {
        campaign.$(function() {
            campaign.logout({reloadWidgets: true});
        });
    }, 200);
    setTimeout(() => {
        var campaign = VL.load("<?= $campaignId; ?>", {
            autoLoadWidgets: !0
        });
        campaign.addHook("boot", function() {
            campaign.widgets.create("rewardingWidget", {
                container: "body",
                position: "bottom-left"
            }), campaign.widgets.create("rewardingWidgetTrigger", {
                container: "body",
                position: "bottom-left"
            })
        });

        campaign.identify({
            firstname: "<?= $block->getCustomer()->getData('firstname'); ?>",
            lastname: "<?= $block->getCustomer()->getData('lastname'); ?>",
            email:  "<?= $block->getCustomer()->getEmail(); ?>",
            createdAt: "<?= $block->getCustomer()->getCreatedAtTimestamp(); ?>"
        });
    }, 2000);
</script>
<?php endif; ?>


